// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {downloader} from '../models';
import {context} from '../models';

export function CancelDownload(arg1:string):Promise<boolean>;

export function ClearHistory():Promise<void>;

export function GetActiveTasks():Promise<Array<downloader.DownloadTask>>;

export function GetAllTasks():Promise<Array<downloader.DownloadTask>>;

export function GetHistoryTasks():Promise<Array<downloader.DownloadTask>>;

export function GetTaskByID(arg1:string):Promise<downloader.DownloadTask>;

export function GetTaskProgress(arg1:string):Promise<Record<string, any>>;

export function Lock():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetStorageAPI(arg1:any):Promise<void>;

export function StartDownload(arg1:string):Promise<string>;

export function TryLock():Promise<boolean>;

export function Unlock():Promise<void>;
