// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['downloader']['DownloaderAPI']['CancelDownload'](arg1);
}

export function ClearHistory() {
  return window['go']['downloader']['DownloaderAPI']['ClearHistory']();
}

export function GetActiveTasks() {
  return window['go']['downloader']['DownloaderAPI']['GetActiveTasks']();
}

export function GetAllTasks() {
  return window['go']['downloader']['DownloaderAPI']['GetAllTasks']();
}

export function GetHistoryTasks() {
  return window['go']['downloader']['DownloaderAPI']['GetHistoryTasks']();
}

export function GetTaskByID(arg1) {
  return window['go']['downloader']['DownloaderAPI']['GetTaskByID'](arg1);
}

export function GetTaskProgress(arg1) {
  return window['go']['downloader']['DownloaderAPI']['GetTaskProgress'](arg1);
}

export function Lock() {
  return window['go']['downloader']['DownloaderAPI']['Lock']();
}

export function SetStorageAPI(arg1) {
  return window['go']['downloader']['DownloaderAPI']['SetStorageAPI'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['downloader']['DownloaderAPI']['StartDownload'](arg1);
}

export function TryLock() {
  return window['go']['downloader']['DownloaderAPI']['TryLock']();
}

export function Unlock() {
  return window['go']['downloader']['DownloaderAPI']['Unlock']();
}
