// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {storage} from '../models';

export function AddDownloadRecord(arg1:any):Promise<void>;

export function AddLibrary(arg1:string):Promise<boolean>;

export function ClearDownloadHistory():Promise<void>;

export function GetDownloadHistory():Promise<Array<models.DownloadTask>>;

export function GetLibraries():Promise<Array<string>>;

export function GetOutputDir():Promise<string>;

export function GetProxy():Promise<string>;

export function GetStorage():Promise<storage.Storage>;

export function SetOutputDir(arg1:string):Promise<boolean>;

export function SetProxy(arg1:string):Promise<boolean>;
