// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownloadRecord(arg1) {
  return window['go']['storage']['StorageAPI']['AddDownloadRecord'](arg1);
}

export function AddLibrary(arg1) {
  return window['go']['storage']['StorageAPI']['AddLibrary'](arg1);
}

export function ClearDownloadHistory() {
  return window['go']['storage']['StorageAPI']['ClearDownloadHistory']();
}

export function GetDownloadHistory() {
  return window['go']['storage']['StorageAPI']['GetDownloadHistory']();
}

export function GetLibraries() {
  return window['go']['storage']['StorageAPI']['GetLibraries']();
}

export function GetOutputDir() {
  return window['go']['storage']['StorageAPI']['GetOutputDir']();
}

export function GetProxy() {
  return window['go']['storage']['StorageAPI']['GetProxy']();
}

export function GetStorage() {
  return window['go']['storage']['StorageAPI']['GetStorage']();
}

export function SetOutputDir(arg1) {
  return window['go']['storage']['StorageAPI']['SetOutputDir'](arg1);
}

export function SetProxy(arg1) {
  return window['go']['storage']['StorageAPI']['SetProxy'](arg1);
}
