// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {storage} from '../models';

export function AddDownloadRecord(arg1:any):Promise<void>;

export function ClearDownloadHistory():Promise<void>;

export function GetDownloadHistory():Promise<Array<dto.DownloadTaskDTO>>;

export function GetStorage():Promise<storage.Manager>;
