// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownloadRecord(arg1) {
  return window['go']['storage']['API']['AddDownloadRecord'](arg1);
}

export function ClearDownloadHistory() {
  return window['go']['storage']['API']['ClearDownloadHistory']();
}

export function GetDownloadHistory() {
  return window['go']['storage']['API']['GetDownloadHistory']();
}

export function GetStorage() {
  return window['go']['storage']['API']['GetStorage']();
}
