// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CrawlFromWeb(arg1, arg2) {
  return window['go']['viewer']['Viewer']['CrawlFromWeb'](arg1, arg2);
}

export function DeleteManga(arg1) {
  return window['go']['viewer']['Viewer']['DeleteManga'](arg1);
}

export function GetAllMangas() {
  return window['go']['viewer']['Viewer']['GetAllMangas']();
}

export function GetImageDataUrl(arg1) {
  return window['go']['viewer']['Viewer']['GetImageDataUrl'](arg1);
}

export function GetLibraries() {
  return window['go']['viewer']['Viewer']['GetLibraries']();
}

export function GetMangaImages(arg1) {
  return window['go']['viewer']['Viewer']['GetMangaImages'](arg1);
}

export function GetOSType() {
  return window['go']['viewer']['Viewer']['GetOSType']();
}

export function GetOutputDir() {
  return window['go']['viewer']['Viewer']['GetOutputDir']();
}

export function GetPathSeparator() {
  return window['go']['viewer']['Viewer']['GetPathSeparator']();
}

export function GetProxy() {
  return window['go']['viewer']['Viewer']['GetProxy']();
}

export function LoadAllLibraries() {
  return window['go']['viewer']['Viewer']['LoadAllLibraries']();
}

export function LoadLibrary(arg1) {
  return window['go']['viewer']['Viewer']['LoadLibrary'](arg1);
}

export function NotifyDownloadProgress(arg1, arg2) {
  return window['go']['viewer']['Viewer']['NotifyDownloadProgress'](arg1, arg2);
}

export function SelectLibrary() {
  return window['go']['viewer']['Viewer']['SelectLibrary']();
}

export function SetOutputDir() {
  return window['go']['viewer']['Viewer']['SetOutputDir']();
}

export function SetProxy(arg1) {
  return window['go']['viewer']['Viewer']['SetProxy'](arg1);
}

export function Startup(arg1) {
  return window['go']['viewer']['Viewer']['Startup'](arg1);
}
