// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {getter} from '../models';
import {viewer} from '../models';

export function CrawlFromWeb(arg1:string,arg2:string):Promise<string>;

export function DeleteManga(arg1:string):Promise<boolean>;

export function GetAllMangas():Promise<Array<getter.Manga>>;

export function GetImageDataUrl(arg1:string):Promise<string>;

export function GetLibraries():Promise<Array<string>>;

export function GetMangaImages(arg1:string):Promise<Array<string>>;

export function GetOSType():Promise<string>;

export function GetOutputDir():Promise<string>;

export function GetPathSeparator():Promise<string>;

export function LoadAllLibraries():Promise<void>;

export function LoadConfig():Promise<boolean>;

export function LoadLibrary(arg1:string):Promise<boolean>;

export function NotifyDownloadProgress(arg1:number,arg2:number):Promise<void>;

export function SaveConfig():Promise<boolean>;

export function SelectLibrary():Promise<string>;

export function SetOutputDir():Promise<string>;

export function SubscribeToDownloadProgress(arg1:viewer.DownloadProgressCallback):Promise<void>;

export function UnsubscribeFromDownloadProgress():Promise<void>;

export function UpdateDownloaderProgress(arg1:number,arg2:number):Promise<void>;
