// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['api']['DownloadAPI']['CancelDownload'](arg1);
}

export function ClearHistory() {
  return window['go']['api']['DownloadAPI']['ClearHistory']();
}

export function GetActiveTasks() {
  return window['go']['api']['DownloadAPI']['GetActiveTasks']();
}

export function GetAllTasks() {
  return window['go']['api']['DownloadAPI']['GetAllTasks']();
}

export function GetHistoryTasks() {
  return window['go']['api']['DownloadAPI']['GetHistoryTasks']();
}

export function GetTaskByID(arg1) {
  return window['go']['api']['DownloadAPI']['GetTaskByID'](arg1);
}

export function GetTaskProgress(arg1) {
  return window['go']['api']['DownloadAPI']['GetTaskProgress'](arg1);
}

export function Lock() {
  return window['go']['api']['DownloadAPI']['Lock']();
}

export function SetContext(arg1) {
  return window['go']['api']['DownloadAPI']['SetContext'](arg1);
}

export function SetStorageAPI(arg1) {
  return window['go']['api']['DownloadAPI']['SetStorageAPI'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['api']['DownloadAPI']['StartDownload'](arg1);
}

export function TryLock() {
  return window['go']['api']['DownloadAPI']['TryLock']();
}

export function Unlock() {
  return window['go']['api']['DownloadAPI']['Unlock']();
}
