// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteManga(arg1:string):Promise<boolean>;

export function GetAllMangas():Promise<Array<main.Manga>>;

export function GetImageDataUrl(arg1:string):Promise<string>;

export function GetImagesInDir(arg1:string):Promise<Array<string>>;

export function GetLibraries():Promise<Array<string>>;

export function GetMangaImages(arg1:string):Promise<Array<string>>;

export function GetOSType():Promise<string>;

export function GetPathSeparator():Promise<string>;

export function LoadAllLibraries():Promise<void>;

export function LoadConfig():Promise<boolean>;

export function LoadLibrary(arg1:string):Promise<boolean>;

export function SaveConfig():Promise<boolean>;

export function SelectLibrary():Promise<string>;

export function SortImages(arg1:Array<string>):Promise<void>;
