// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteManga(arg1) {
  return window['go']['main']['App']['DeleteManga'](arg1);
}

export function GetAllMangas() {
  return window['go']['main']['App']['GetAllMangas']();
}

export function GetImageDataUrl(arg1) {
  return window['go']['main']['App']['GetImageDataUrl'](arg1);
}

export function GetImagesInDir(arg1) {
  return window['go']['main']['App']['GetImagesInDir'](arg1);
}

export function GetLibraries() {
  return window['go']['main']['App']['GetLibraries']();
}

export function GetMangaImages(arg1) {
  return window['go']['main']['App']['GetMangaImages'](arg1);
}

export function GetOSType() {
  return window['go']['main']['App']['GetOSType']();
}

export function GetPathSeparator() {
  return window['go']['main']['App']['GetPathSeparator']();
}

export function LoadAllLibraries() {
  return window['go']['main']['App']['LoadAllLibraries']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadLibrary(arg1) {
  return window['go']['main']['App']['LoadLibrary'](arg1);
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SelectLibrary() {
  return window['go']['main']['App']['SelectLibrary']();
}

export function SortImages(arg1) {
  return window['go']['main']['App']['SortImages'](arg1);
}
