// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CrawlFromWeb(arg1, arg2) {
  return window['go']['main']['Viewer']['CrawlFromWeb'](arg1, arg2);
}

export function DeleteManga(arg1) {
  return window['go']['main']['Viewer']['DeleteManga'](arg1);
}

export function GetAllMangas() {
  return window['go']['main']['Viewer']['GetAllMangas']();
}

export function GetImageDataUrl(arg1) {
  return window['go']['main']['Viewer']['GetImageDataUrl'](arg1);
}

export function GetLibraries() {
  return window['go']['main']['Viewer']['GetLibraries']();
}

export function GetMangaImages(arg1) {
  return window['go']['main']['Viewer']['GetMangaImages'](arg1);
}

export function GetOSType() {
  return window['go']['main']['Viewer']['GetOSType']();
}

export function GetOutputDir() {
  return window['go']['main']['Viewer']['GetOutputDir']();
}

export function GetPathSeparator() {
  return window['go']['main']['Viewer']['GetPathSeparator']();
}

export function LoadAllLibraries() {
  return window['go']['main']['Viewer']['LoadAllLibraries']();
}

export function LoadConfig() {
  return window['go']['main']['Viewer']['LoadConfig']();
}

export function LoadLibrary(arg1) {
  return window['go']['main']['Viewer']['LoadLibrary'](arg1);
}

export function SaveConfig() {
  return window['go']['main']['Viewer']['SaveConfig']();
}

export function SelectLibrary() {
  return window['go']['main']['Viewer']['SelectLibrary']();
}

export function SetOutputDir() {
  return window['go']['main']['Viewer']['SetOutputDir']();
}
